### ISSUE TITLE
Add Typescript typings

### ISSUE THREAD

**Issue by PaulInglis** [locize/locize#153]
When using locize in a typescript project I get the error:
```
TypeScript error: Could not find a declaration file for module 'locize'. 'D:/MyApp/App/node_modules/locize/index.js' implicitly has an 'any' type.
  Try `npm install @types/locize` if it exists or add a new declaration (.d.ts) file containing `declare module 'locize';`  TS7016

  > 1 | import i18n from 'locize';
      |                  ^
    2 | 
.
.
.
```

Running `npm install @types/locize` doesn't work as there is no such package, so could the Typescript typings be added to the locize package, or in a separate typings package pleas?

**Comment by jamuhl** [comment]
Hi @PaulInglis - i almost forgot about this package...honestly we should / will deprecate this as it does not really add benefits over hooking up i18next directly and get the updates done there immediatly. 

This module just wraps i18next add the language-detector and locize-backend: https://github.com/locize/locize/blob/master/src/index.js

In i18next you also got the typings in latest version.

So basically just do:

`npm i i18next i18next-browser-languagedetector i18next-locize-backend --save`

and in your i18n.js

```js
import i18next from 'i18next';
import LocizeBackend from 'i18next-locize-backend';
import LanguageDetector from 'i18next-browser-languagedetector';

i18next
  .use(LocizeBackend)
  .use(LanguageDetector);
  .init({
    fallbackLng: 'en',
    backend: {
      projectId: '[PROJECT_ID]',
      apiKey: '[API_KEY]',
      referenceLng: 'en'
    }
  });

export default i18next;
```

**Comment by danielo515** [comment]
Is this package going to be deprecated? What about the live editor for translation strings? Is that functionality also going to be removed?

**Comment by jamuhl** [comment]
@danielo515 this issue was before we changed the locize script completely (before it was some sort of clone of i18next -> i18next with bundled i18next-locize-backend) which was like commented rather useless.

To be able to use the locize name on npm we decided to use this module now for our v3 UI which comes with the new InContext Editor (this module is needed to get that work using the postMessage API)

https://docs.locize.com/more/incontext-editor/migrating-from-the-old-incontext-editor

So, the old version/usage was already deprecated and the new one will at least stay as long the current locize UI exists.

**Comment by danielo515** [comment]
Ok, thanks for clarification. I just started using this library for the focus editor and I was worried about using a deprecated library
